export const SELECTED_CATEGORY = 'SELECTED_CATEGORY';
export const CATEGORY_DATA_SUCCESS = 'CATEGORY_DATA_SUCCESS';
export const SELECTED_DISH = 'SELECTED_DISH';
export const DISH_DATA_SUCCESS = 'DISH_DATA_SUCCESS';
