export const GET_DISHES = 'GET_DISHES';
export const GET_DISHES_SUCCESS = 'GET_DISHES_SUCCESS';
export const GET_DISHES_FAILURE = 'GET_DISHES_FAILURE';

export const GET_DISH = 'GET_DISH';
export const GET_DISH_SUCCESS = 'GET_DISH_SUCCESS';
export const GET_DISH_FAILURE = 'GET_DISH_FAILURE';


export const DELETE_DISH = 'DELETE_DISH';
export const DELETE_DISH_SUCCESS = 'DELETE_DISH_SUCCESS';
export const DELETE_DISH_FAILURE = 'DELETE_DISH_FAILURE';

export const POST_DISH = 'POST_DISH';
export const POST_DISH_SUCCESS = 'POST_DISH_SUCCESS';
export const POST_DISH_FAILURE = 'POST_DISH_FAILURE';