export const UPLOAD_PICTURE = 'UPLOAD_PICTURE';
export const UPLOAD_PICTURE_SUCCESS = 'UPLOAD_PICTURE_SUCCESS';
export const UPLOAD_PICTURE_FAILURE = 'UPLOAD_PICTURE_FAILURE';

export const REMOVE_PICTURE = 'REMOVE_PICTURE';
export const REMOVE_PICTURE_SUCCESS = 'REMOVE_PICTURE_SUCCESS';
export const REMOVE_PICTURE_FAILURE = 'REMOVE_PICTURE_FAILURE';